SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[SUBJECT_BY_ID]
(
  @P_SUBJECT_ID VARCHAR(15) = NULL,
  @P_USER_LOGIN VARCHAR(100) = NULL
)
AS
BEGIN
	SELECT * FROM SUBJECT S
  WHERE S.SUBJECT_ID = @P_SUBJECT_ID
END
GO