SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[CLASS_INS]
(
  @P_CLASS_CODE VARCHAR(15) = NULL,
  @P_CLASS_NAME NVARCHAR(300) = NULL,
  @P_SUBJECT_ID VARCHAR(15) = NULL,
  @P_TEACHER_NAME NVARCHAR(300) = NULL,
  @P_DEP_ID VARCHAR(15) = NULL,
  @P_QUANTITY VARCHAR(15) = NULL,
  @P_START_DT  VARCHAR(30) = NULL,
  @P_END_DT  VARCHAR(30) = NULL,
  @P_MAKER_ID  VARCHAR(50) = NULL
)
AS
BEGIN
  DECLARE @P_CLASS_ID VARCHAR(15)
	-- VALIDATE HERE
  IF(EXISTS(SELECT 1 FROM CLASS WHERE CLASS_CODE = @P_CLASS_CODE AND AUTH_STATUS = 'A' AND RECORD_STATUS = 1))
  BEGIN
    SELECT -1 STATUS_CODE, N'Mã lớp đã tồn tại' ERROR_MESSAGE
    RETURN -1
  END
  IF(NOT EXISTS(SELECT 1 FROM SUBJECT WHERE SUBJECT_ID = @P_SUBJECT_ID AND AUTH_STATUS = 'A' AND RECORD_STATUS = 1))
  BEGIN
    SELECT -1 STATUS_CODE, N'Môn học không tồn tại' ERROR_MESSAGE
    RETURN -1
  END
  BEGIN TRANSACTION
  EXEC SYS_CodeMasters_Gen 'CLASS', @P_CLASS_ID
  IF (@P_CLASS_ID IS NULL OR @P_CLASS_ID = '')
  GOTO ABORT

  INSERT INTO CLASS(CLASS_ID, CLASS_CODE, CLASS_NAME, SUBJECT_ID, TEACHER_NAME, DEP_ID, QUANTITY, START_DT,
  END_DT, MAKER_ID, CREATE_DT,AUTH_STATUS, RECORD_STATUS)
  VALUES(@P_CLASS_ID, @P_CLASS_CODE, @P_CLASS_NAME, @P_SUBJECT_ID, @P_TEACHER_NAME, @P_DEP_ID, @P_QUANTITY, @P_START_DT
  , @P_END_DT, @P_MAKER_ID, GETDATE(), 'D', 1)
  IF @@error <> 0 GOTO ABORT

  COMMIT TRANSACTION
  SELECT 0 STATUS_CODE, @P_CLASS_ID CLASS_ID,'' ERROR_MESSAGE
  RETURN 0

  ABORT:
  BEGIN
    ROLLBACK TRANSACTION
    SELECT -1 STATUS_CODE, '' ERROR_MESSAGE
    RETURN -1
  END
END
GO