SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[ENROLLED_STUDENT_SEARCH]
(
  @P_ENROLLED_ID VARCHAR(15) = NULL,
  @P_STUDENT_ID VARCHAR(15) = NULL,
  @P_SUBJECT_ID VARCHAR(15) = NULL,
  @P_CLASS_ID VARCHAR(15) = NULL,
  @P_IS_FINISH VARCHAR(1) = NULL,
  @P_AUTH_STATUS VARCHAR(1) = NULL,
  @P_FROM_DT VARCHAR(30) = NULL,
  @P_TO_DT VARCHAR(30) = NULL,
  @P_USER_LOGIN VARCHAR(100) = NULL
)
AS
BEGIN
	SELECT * FROM ENROLLED_STUDENT ES
  WHERE 1=1
  AND (ES.ENROLLED_ID = @P_ENROLLED_ID OR @P_ENROLLED_ID IS NULL OR @P_ENROLLED_ID = '')
  AND (ES.SUBJECT_ID = @P_STUDENT_ID OR @P_STUDENT_ID IS NULL OR @P_STUDENT_ID = '')
  AND (ES.SUBJECT_ID = @P_SUBJECT_ID OR @P_SUBJECT_ID IS NULL OR @P_SUBJECT_ID = '')
  AND (ES.CLASS_ID = @P_CLASS_ID OR @P_CLASS_ID IS NULL OR @P_CLASS_ID = '')
  AND (ES.IS_FINISH = CONVERT(BIT, @P_IS_FINISH) OR @P_IS_FINISH IS NULL OR @P_IS_FINISH = '')
  AND (ES.AUTH_STATUS = @P_AUTH_STATUS OR @P_AUTH_STATUS IS NULL OR @P_AUTH_STATUS = '')
  AND (CONVERT(DATE, ES.CREATE_DT) >= CONVERT(DATE, @P_FROM_DT) OR @P_FROM_DT IS NULL OR @P_FROM_DT = '')
  AND (CONVERT(DATE, ES.CREATE_DT) <= CONVERT(DATE, @P_TO_DT) OR @P_TO_DT IS NULL OR @P_TO_DT = '')
  AND (ES.STUDENT_ID = @P_USER_LOGIN OR @P_USER_LOGIN IS NULL OR @P_USER_LOGIN = '')
  AND ES.RECORD_STATUS = 1
END

GO