SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[CLASS_BY_ID]
(
  @P_CLASS_ID VARCHAR(15) = NULL,
  @P_USER_LOGIN VARCHAR(100) = NULL
)
AS
BEGIN
	SELECT * FROM CLASS C
  WHERE C.CLASS_ID = @P_CLASS_ID
END
GO