CREATE TABLE [dbo].[CLASS] (
  [CLASS_ID] [nvarchar](450) NOT NULL,
  [CLASS_CODE] [nvarchar](max) NULL,
  [CLASS_NAME] [nvarchar](max) NULL,
  [SUBJECT_ID] [nvarchar](max) NULL,
  [TEACHER_NAME] [nvarchar](max) NULL,
  [DEP_ID] [nvarchar](max) NULL,
  [QUANTITY] [int] NOT NULL,
  [START_DT] [datetime2] NULL,
  [END_DT] [datetime2] NULL,
  [MAKER_ID] [nvarchar](max) NULL,
  [CREATE_DT] [datetime2] NULL,
  [CHECKER_ID] [nvarchar](max) NULL,
  [APPROVE_DT] [datetime2] NULL,
  [AUTH_STATUS] [nvarchar](max) NULL,
  [RECORD_STATUS] [int] NOT NULL,
  [SUBJECT_ENTITYSUBJECT_ID] [nvarchar](450) NULL,
  [CURRENT_QUANTITY] [int] NOT NULL DEFAULT (0),
  CONSTRAINT [PK_CLASS] PRIMARY KEY CLUSTERED ([CLASS_ID])
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

CREATE INDEX [IX_CLASS_SUBJECT_ENTITYSUBJECT_ID]
  ON [dbo].[CLASS] ([SUBJECT_ENTITYSUBJECT_ID])
  ON [PRIMARY]
GO

ALTER TABLE [dbo].[CLASS]
  ADD CONSTRAINT [FK_CLASS_SUBJECT_SUBJECT_ENTITYSUBJECT_ID] FOREIGN KEY ([SUBJECT_ENTITYSUBJECT_ID]) REFERENCES [dbo].[SUBJECT] ([SUBJECT_ID])
GO