CREATE TABLE [dbo].[DEPARTMENT] (
  [DEP_ID] [nvarchar](450) NOT NULL,
  [DEP_CODE] [nvarchar](max) NOT NULL,
  [DEP_NAME] [nvarchar](max) NOT NULL,
  CONSTRAINT [PK_DEPARTMENT] PRIMARY KEY CLUSTERED ([DEP_ID])
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO