CREATE TABLE [dbo].[ENROLLED_STUDENT] (
  [ENROLLED_ID] [nvarchar](450) NOT NULL,
  [STUDENT_ID] [nvarchar](max) NOT NULL,
  [IS_FINISH] [bit] NOT NULL,
  [CREATE_DT] [datetime2] NULL,
  [AUTH_STATUS] [nvarchar](max) NOT NULL,
  [RECORD_STATUS] [int] NOT NULL,
  [STUDENTId] [nvarchar](450) NULL,
  [SUBJECT_ID] [nvarchar](max) NOT NULL DEFAULT (N''),
  [CLASS_ID] [nvarchar](max) NOT NULL DEFAULT (N''),
  [DEPARTMENTDEP_ID] [nvarchar](450) NULL,
  [CLASS_ID1] [nvarchar](450) NULL,
  [SUBJECT_ID1] [nvarchar](450) NULL,
  CONSTRAINT [PK_ENROLLED_STUDENT] PRIMARY KEY CLUSTERED ([ENROLLED_ID])
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

CREATE INDEX [IX_ENROLLED_STUDENT_CLASS_ID1]
  ON [dbo].[ENROLLED_STUDENT] ([CLASS_ID1])
  ON [PRIMARY]
GO

CREATE INDEX [IX_ENROLLED_STUDENT_DEPARTMENTDEP_ID]
  ON [dbo].[ENROLLED_STUDENT] ([DEPARTMENTDEP_ID])
  ON [PRIMARY]
GO

CREATE INDEX [IX_ENROLLED_STUDENT_STUDENTId]
  ON [dbo].[ENROLLED_STUDENT] ([STUDENTId])
  ON [PRIMARY]
GO

CREATE INDEX [IX_ENROLLED_STUDENT_SUBJECT_ID1]
  ON [dbo].[ENROLLED_STUDENT] ([SUBJECT_ID1])
  ON [PRIMARY]
GO

ALTER TABLE [dbo].[ENROLLED_STUDENT]
  ADD CONSTRAINT [FK_ENROLLED_STUDENT_AspNetUsers_STUDENTId] FOREIGN KEY ([STUDENTId]) REFERENCES [dbo].[AspNetUsers] ([Id])
GO

ALTER TABLE [dbo].[ENROLLED_STUDENT]
  ADD CONSTRAINT [FK_ENROLLED_STUDENT_CLASS_CLASS_ID1] FOREIGN KEY ([CLASS_ID1]) REFERENCES [dbo].[CLASS] ([CLASS_ID])
GO

ALTER TABLE [dbo].[ENROLLED_STUDENT]
  ADD CONSTRAINT [FK_ENROLLED_STUDENT_DEPARTMENT_DEPARTMENTDEP_ID] FOREIGN KEY ([DEPARTMENTDEP_ID]) REFERENCES [dbo].[DEPARTMENT] ([DEP_ID])
GO

ALTER TABLE [dbo].[ENROLLED_STUDENT]
  ADD CONSTRAINT [FK_ENROLLED_STUDENT_SUBJECT_SUBJECT_ID1] FOREIGN KEY ([SUBJECT_ID1]) REFERENCES [dbo].[SUBJECT] ([SUBJECT_ID])
GO