CREATE TABLE [dbo].[REQUIRED_SUBJECT] (
  [REQUIRED_SUBJECT_ID] [nvarchar](450) NOT NULL,
  [MAKER_ID] [nvarchar](max) NOT NULL,
  [CREATE_DT] [datetime2] NULL,
  [CHECKER_ID] [nvarchar](max) NOT NULL,
  [APPROVE_DT] [datetime2] NULL,
  [AUTH_STATUS] [nvarchar](max) NOT NULL,
  [RECORD_STATUS] [int] NOT NULL,
  [SUBJECT_ID] [nvarchar](450) NOT NULL DEFAULT (N''),
  CONSTRAINT [PK_REQUIRED_SUBJECT] PRIMARY KEY CLUSTERED ([SUBJECT_ID], [REQUIRED_SUBJECT_ID])
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[REQUIRED_SUBJECT]
  ADD CONSTRAINT [FK_REQUIRED_SUBJECT_SUBJECT_SUBJECT_ID] FOREIGN KEY ([SUBJECT_ID]) REFERENCES [dbo].[SUBJECT] ([SUBJECT_ID]) ON DELETE CASCADE
GO